### ISSUE TITLE
Not able to connect DB2 database

### ISSUE THREAD

**Issue by Vani2468** [lausser/check_db2_health#10]
We are trying to connect DB2 database using check_db2_health plugin.

From command line we are getting correct output 

**/omd/plugins/check_db2_health --username xxxx --password xxxx --hostname xxxx --mode xxxx --database xxxx --port xxxx --warning 5 --critical 6**

but from Thruk we are getting below critical error

**CRITICAL: cannot connect to database. Total Environment allocation failure! Did you set up your DB2 client environment ?**

I have installed db2 client, DBI, DBD::DB2 module.

Kindly advice how to resolve the error from Thruk.

**Comment by lausser** [comment]
This AI assistant might be right. I also would say that it's a difference in the environment variables which you see on the command line and which the Naemon core sees.
On the command line check and variables with *DB2* and LD_LIBRARY_PATH. If you find anything IBM-related, then copy it to
etc/environment in the OMD site.
Exit, login again (so that your session has the new environment) and run "omd restart naemon"
If you have dedicated gearman worker nodes, the same applies here as well.

**Comment by Vani2468** [comment]
Thanks to AI assistant and Gerhard.

Adding environment variables in etc/environment in the OMD site fixed the issue.
